### PR TITLE
Add a package.json, .gitignore

### LINKED ISSUE #2: Add License and Package JSON file
Would be great to get this package into [NPM](https://www.npmjs.com/).

Could you please create a package.json file for this using ```npm init``` as well as adding a LICENSE file and noting it within the package.json file as well as your README?

Thanks! :)

### PR DESCRIPTION
**Pull request by brandly**
hey @jimreesman!

this basically fixes #2. i've listed the license as `MIT`. maybe you want [something different](http://choosealicense.com/).

the license, along with explicitly listing dependencies, will make this easier to use. people can interact with the repo by just cloning the repo, running `npm install`, adding their API keys, and running `node clarifai_sample.js`.

also, if you're all set up on `npm`, _you_ should be able to run `npm publish`, which will publish the package `clarifai` at version `1.0.0`, as listed in the `package.json`. [this link](https://docs.npmjs.com/getting-started/publishing-npm-packages) might explain things better.

i hope this helps! :star2:

### CODE REVIEW

**Comment by brandly** [comment]
shout outs to @cassidoo for bringing this to my attention on facebook

**Comment by cassidoo** [comment]
@brandly <3

**Comment by abdulhannanali** [comment]
I think it's great, so why isn't it getting merged!!!

**Comment by dankantor** [comment]
Looks like there is now a published `clarifai` module on NPM which isn't ours - https://www.npmjs.com/package/clarifai

We are working on an updated client which we will publish to NPM. Not ready yet though.

**Comment by abdulhannanali** [comment]
@dankantor cool!

**Comment by dankantor** [comment]
We now own https://www.npmjs.com/package/clarifai. Please use that!

**Comment by brandly** [comment]
Thanks Dan!

**Pull request closed without merging**
